services:
  client:
    build:
      context: ./client
    ports:
      - "${CLIENT_PORT:-3000}:80"
    depends_on:
      - server
    env_file:
      - ./client/.env
    restart: unless-stopped
    networks:
      - chatnest-network

  server:
    build:
      context: ./server
    ports:
      - "${SERVER_PORT:-5001}:5001"
    depends_on:
      - mongodb
    env_file:
      - ./server/.env
    restart: unless-stopped
    networks:
      - chatnest-network

  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "${MONGO_PORT:-27017}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-chatNest}
    volumes:
      - mongodb_data:/data/db
    networks:
      - chatnest-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
      ME_CONFIG_BASICAUTH: true
    networks:
      - chatnest-network

volumes:
  mongodb_data:

networks:
  chatnest-network:
    driver: bridge
